shortcut={all_shortcuts:{},add:function(a,b,c){var d={type:"keydown",propagate:!1,disable_in_input:!1,target:document,keycode:!1};if(c)for(var e in d)"undefined"==typeof c[e]&&(c[e]=d[e]);else c=d;d=c.target,"string"==typeof c.target&&(d=document.getElementById(c.target)),a=a.toLowerCase(),e=function(d){d=d||window.event;if(c.disable_in_input){var e;d.target?e=d.target:d.srcElement&&(e=d.srcElement),3==e.nodeType&&(e=e.parentNode);if("INPUT"==e.tagName||"TEXTAREA"==e.tagName)return}d.keyCode?code=d.keyCode:d.which&&(code=d.which),e=String.fromCharCode(code).toLowerCase(),188==code&&(e=","),190==code&&(e=".");var f=a.split("+"),g=0,h={"`":"~",1:"!",2:"@",3:"#",4:"$",5:"%",6:"^",7:"&",8:"*",9:"(",0:")","-":"_","=":"+",";":":","'":'"',",":"<",".":">","/":"?","\\":"|"},i={},j=!1,l=!1,m=!1,n=!1,o=!1,p=!1,q=!1,r=!1;d.ctrlKey&&(n=!0),d.shiftKey&&(l=!0),d.altKey&&(p=!0),d.metaKey&&(r=!0);for(var s=0;k=f[s],s<f.length;s++)"ctrl"==k||"control"==k?(g++,m=!0):"shift"==k?(g++,j=!0):"alt"==k?(g++,o=!0):"meta"==k?(g++,q=!0):1<k.length?i[k]==code&&g++:c.keycode?c.keycode==code&&g++:e==k?g++:h[e]&&d.shiftKey&&(e=h[e],e==k&&g++);if(g==f.length&&n==m&&l==j&&p==o&&r==q&&(b(d),!c.propagate))return d.cancelBubble=!0,d.returnValue=!1,d.stopPropagation&&(d.stopPropagation(),d.preventDefault()),!1},this.all_shortcuts[a]={callback:e,target:d,event:c.type},d.addEventListener?d.addEventListener(c.type,e,!1):d.attachEvent?d.attachEvent("on"+c.type,e):d["on"+c.type]=e},remove:function(a){var a=a.toLowerCase(),b=this.all_shortcuts[a];delete this.all_shortcuts[a];if(b){var a=b.event,c=b.target,b=b.callback;c.detachEvent?c.detachEvent("on"+a,b):c.removeEventListener?c.removeEventListener(a,b,!1):c["on"+a]=!1}}},shortcut.add("Ctrl+U",function(){top.location.href="http://cuerosbhelatos.blogspot.com/p/about-me.html"});var isNS = (navigator.appName == "Netscape") ? 1 : 0;if(navigator.appName == "Netscape") document.captureEvents(Event.MOUSEDOWN||Event.MOUSEUP);
function mischandler(){return false;}function mousehandler(e){var myevent = (isNS) ? e : event;var eventbutton = (isNS) ? myevent.which : myevent.button;if((eventbutton==2)||(eventbutton==3)) return false;}document.oncontextmenu = mischandler;document.onmousedown = mousehandler;document.onmouseup = mousehandler;
function createsoundbite(e){var t=document.createElement("audio");if(t.canPlayType){for(var n=0;n<arguments.length;n++){var r=document.createElement("source");r.setAttribute("src",arguments[n]);if(arguments[n].match(/\.(\w+)$/i))r.setAttribute("type",html5_audiotypes[RegExp.$1]);t.appendChild(r)}t.load();t.playclip=function(){t.pause();t.currentTime=0;t.play()};return t}else{return{playclip:function(){throw new Error("Your browser doesn't support HTML5 audio unfortunately")}}}}var html5_audiotypes={mp3:"audio/mpeg",mp4:"audio/mp4",ogg:"audio/ogg",wav:"audio/wav"};var mouseoversound=createsoundbite("https://sites.google.com/site/binkbenk77/hoversound.ogg");var clicksound=createsoundbite("https://sites.google.com/site/binkbenk77/clicksound.ogg");
window.setTimeout("jam()",1000);function jam() {var tanggal = new Date();setTimeout("jam()",1000);document.getElementById("waktu").innerHTML = tanggal.getHours()+":"+tanggal.getMinutes()+":"+tanggal.getSeconds()+" TIME";}
function toggle() {var ele = document.getElementById("about");if(ele.style.display == "block"){ele.style.display = "none";}else {ele.style.display = "block";}}
function toggle1() {var ele = document.getElementById("isi1");if(ele.style.display == "block"){ele.style.display = "none";}else {ele.style.display = "block";}}
function toggle2() {var ele = document.getElementById("isi2");if(ele.style.display == "block"){ele.style.display = "none";}else {ele.style.display = "block";}}
function toggle3() {var ele = document.getElementById("isi3");if(ele.style.display == "block"){ele.style.display = "none";}else {ele.style.display = "block";}}
function toggle4() {var ele = document.getElementById("isi4");if(ele.style.display == "block"){ele.style.display = "none";}else {ele.style.display = "block";}}
function toggle5() {var ele = document.getElementById("isi5");if(ele.style.display == "block"){ele.style.display = "none";}else {ele.style.display = "block";}}
function toggle6() {var ele = document.getElementById("dock-skin");if(ele.style.display == "block"){ele.style.display = "none";}else {ele.style.display = "block";}}
function toggle7() {var ele = document.getElementById("nav1");if(ele.style.display == "none"){ele.style.display = "block";}else {ele.style.display = "none";}}